### ISSUE TITLE
phpmd check fail on hhvm build (Fatal error: Uncaught Error: unknown class Container)

### ISSUE THREAD

**Issue by xKerman** [xKerman/restricted-unserialize#69]
see: https://travis-ci.org/xKerman/restricted-unserialize/jobs/377993599
```
Fatal error: Uncaught Error: unknown class Container in /home/travis/build/xKerman/restricted-unserialize/vendor/symfony/dependency-injection/ContainerBuilder.php:50
Stack trace:
#0 /home/travis/build/xKerman/restricted-unserialize/vendor/composer/ClassLoader.php(444): include()
#1 /home/travis/build/xKerman/restricted-unserialize/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile()
#2 /home/travis/build/xKerman/restricted-unserialize/vendor/pdepend/pdepend/src/main/php/PDepend/Application.php(135): Composer\Autoload\ClassLoader->loadClass()
#3 /home/travis/build/xKerman/restricted-unserialize/vendor/pdepend/pdepend/src/main/php/PDepend/Application.php(122): PDepend\Application->createContainer()
#4 /home/travis/build/xKerman/restricted-unserialize/vendor/pdepend/pdepend/src/main/php/PDepend/Application.php(92): PDepend\Application->getContainer()
#5 /home/travis/build/xKerman/restricted-unserialize/vendor/phpmd/phpmd/src/main/php/PHPMD/ParserFactory.php(96): PDepend\Application->getEngine()
#6 /home/travis/build/xKerman/restricted-unserialize/vendor/phpmd/phpmd/src/main/php/PHPMD/ParserFactory.php(75): PHPMD\ParserFactory->createInstance()
#7 /home/travis/build/xKerman/restricted-unserialize/vendor/phpmd/phpmd/src/main/php/PHPMD/PHPMD.php(215): PHPMD\ParserFactory->create()
#8 /home/travis/build/xKerman/restricted-unserialize/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(133): PHPMD\PHPMD->processFiles()
#9 /home/travis/build/xKerman/restricted-unserialize/vendor/phpmd/phpmd/src/main/php/PHPMD/TextUI/Command.php(173): PHPMD\TextUI\Command->run()
#10 /home/travis/build/xKerman/restricted-unserialize/vendor/phpmd/phpmd/src/bin/phpmd(122): PHPMD\TextUI\Command::main()
#11 {main}
Script phpmd src/ text ./phpmd.xml handling the test event returned with error code 255
```

1 week ago, hhvm build result in success: https://travis-ci.org/xKerman/restricted-unserialize/jobs/375163945

hhvm version:
* 1 week ago: 3.25.3
* today: 3.26.1

**Comment by xKerman** [comment]
fixed in #70, build passed.
https://travis-ci.org/xKerman/restricted-unserialize/builds/378014938
